---
- name: install apache 
  hosts: webservers
  become: yes
  gather_facts: false
  vars:
    httpd_packages:
      - httpd
      - python3-mod_wsgi
    apache_test_message: This is a test message

  tasks:

    - name: install httpd service
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ httpd_packages }}"
      notify: restart apache service
  
  handlers:

    - name: restart apache service
      service:
        name: httpd
        state: restarted
        enabled: yes